
apiVersion: v1
kind: Pod
metadata:
  name: kube-manager-deployment
  
  labels:
    podtype: kube-manager
spec:
  containers:
    - name: kube-rs-manager
      image: gcr.io/level-unfolding-299521/kube-pod-test@sha256:f4ff94dc9a5da3de5c4cacb2f0f74292c39b7b9007bfea6a606ce9ec192d366d
      ports:
        - name: kube-rs-manager
          containerPort: 8880
          protocol: TCP
