
apiVersion: v1
kind: Pod
metadata:
  name: kube-manager-deployment
  
  labels:
    podtype: kube-manager
spec:
  containers:
    - name: kube-rs-manager
      image: gcr.io/level-unfolding-299521/github.com/guccialex/kube-rs-manager:latest
      ports:
        - name: kube-rs-manager
          containerPort: 8880
          protocol: TCP
