apiVersion: v1
kind: Pod
metadata:
  name: kube-manager-deployment
  
  labels:
    podtype: kube-manager
spec:
  containers:
    - name: kube-rs-manager
      image: gcr.io/level-unfolding-299521/github.com/guccialex/kube-rs-manager@sha256:0004666011b69fcbb657459894a94c2c61d3788b870bf7664104ece3e1f30370
      ports:
        - name: kube-rs-manager
          containerPort: 8000
          protocol: TCP
