apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-manager-deployment
  labels:
    podtype: kube-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      podtype: kube-manager

  template:

    metadata:
      labels:
        podtype: kube-manager
    spec:
      containers:
        - name: kube-rs-manager
          image: gcr.io/$PROJECT_ID/matchmaker:latest
          ports:
            - name: kube-rs-manager
              containerPort: 8000
              protocol: TCP
