apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-manager-d
  namespace: default
  labels:
    podtype: kube-manager-d
spec:
  replicas: 1
  selector:
    matchLabels:
      podtype: kube-manager-d

  template:

    metadata:
      labels:
        podtype: kube-manager-d
    spec:
      containers:
        - name: kube-rs-manager-d
          image: gcr.io/cheaper-324003/matchmaker:latest
          ports:
            - name: client-port
              containerPort: 8000
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: kube-manager-s
spec:
  selector:
    podtype: kube-manager-d
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000